export const ROOMS = [
	{
		id: 1,
		name: 'Lecture Hall A',
		type: 'Lecture Hall',
		seats: 150,
		status: 'Available',
		features: ['Projector', 'Audio System', 'Whiteboard'],
	},
	{
		id: 2,
		name: 'Seminar Room 3',
		type: 'Seminar Room',
		seats: 30,
		status: 'Occupied',
		features: ['Smart TV', 'Video Conf'],
	},
	{
		id: 3,
		name: 'Lab 4B',
		type: 'Laboratory',
		seats: 40,
		status: 'Maintenance',
		features: ['Workstations', 'Specialized Eq.'],
	},
	{
		id: 4,
		name: 'Conference Room',
		type: 'Meeting Room',
		seats: 20,
		status: 'Available',
		features: ['Projector', 'Whiteboard'],
	},
	{
		id: 5,
		name: 'Study Pod 12',
		type: 'Study Space',
		seats: 4,
		status: 'Available',
		features: ['Monitor', 'Power Outlets'],
	},
	{
		id: 6,
		name: 'Main Auditorium',
		type: 'Auditorium',
		seats: 500,
		status: 'Available',
		features: ['Full AV Setup', 'Stage'],
	},
	{
		id: 7,
		name: 'Innovation Lab 2',
		type: 'Innovation Lab',
		seats: 28,
		status: 'Available',
		features: ['3D Printer', 'Smart Board', 'AC'],
	},
	{
		id: 8,
		name: 'Language Studio 1',
		type: 'Language Room',
		seats: 32,
		status: 'Available',
		features: ['Headsets', 'Projector', 'Recording Desk'],
	},
];
